version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./packer.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      